spring.application.name=Laptop_Shop_Spring_MVC_project

# ===============================
# AIVEN CLOUD DATABASE CONFIGURATION (DIRECT CONNECT)
# ===============================
spring.datasource.url=jdbc:mysql://mysql-18f29867-prathmeshshop.e.aivencloud.com:15573/laptop_db?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
# Yahan ${AIVEN_DB_PASSWORD} ki jagah apna asli password bina brackets ke daal do!
spring.datasource.password=AVNS_usqnMi1W6ggB15I7xS3

# ===============================
# JPA / HIBERNATE & DIALECT CONFIGURATION
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# MVC VIEW RESOLVER (JSP PATH)
# ===============================
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp